"""receipt payment type

Revision ID: 4f926a8669af
Revises: b4017083891f
Create Date: 2025-03-27 22:19:54.011727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f926a8669af'
down_revision: Union[str, None] = 'b4017083891f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts', sa.Column('payment_type', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipts', 'payment_type')
    # ### end Alembic commands ###
