"""stock ref

Revision ID: f0dc4ffca36a
Revises: ce9eb2b013b9
Create Date: 2025-03-27 23:30:54.379493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0dc4ffca36a'
down_revision: Union[str, None] = 'ce9eb2b013b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipts', 'gross_amount')
    op.drop_column('receipts', 'tax')
    op.add_column('stocks', sa.Column('ref', sa.String(), server_default='94ea5908-018b-4cd0-8146-209294d494bb', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'ref')
    op.add_column('receipts', sa.Column('tax', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('receipts', sa.Column('gross_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
